Collaps docker-build pipeline into main pipeline
hoist pipeline config up to `ci/` dir

diff --git a/ci/pipeline.yml b/ci/pipeline.yml
--- a/ci/pipeline.yml
+++ b/ci/pipeline.yml
@@ -2,7 +2,7 @@
 #!  WARNING: this pipeline is automatically set and manual changes will go away. 
 #!
 #!  To set the pipeline manually run:
-#!    fly -t bosh-ecosystem set-pipeline -p bbr-cli -c <(ytt -f ci/pipelines/bbr-cli/pipeline.yml --data-values-file ci/pipelines/bbr-cli/values.yml)
+#!    fly -t bosh-ecosystem set-pipeline -p bbr-cli -c <(ytt -f ci/pipeline.yml --data-values-file ci/pipeline-values.yml)
 
 #@ load("@ytt:data", "data")
 
@@ -13,6 +13,9 @@
 secrets:
 #! gcr_viewer_key is used for getting concourse container images from the Cryogenics GCR instance. Currently bosh-ecosystem-concourse@cf-bosh-concourse.iam.gserviceaccount.com is granted access to the images.
 - &gcr_viewer_key ((gcp_credentials_json))
+
+#! used to upload images to docker registry
+- &gcp_docker_password ((gcp_credentials_json))
 
 #! github_access_token is used to create PRs and fetch github releases.
 - &github_access_token ((github_read_write_token))
@@ -111,6 +114,10 @@ groups:
   jobs:
   - bump-golang
   - bump-go-module
+
+- name: registry-images
+  jobs:
+  - build-bbr-pcf-pipeline-tasks
 
 resource_types:
 - name: gitlab
@@ -407,6 +414,45 @@ resources:
       pool:
         namespace: official
         name: cfd
+
+- name: ubuntu-lts
+  type: registry-image
+  source:
+    repository: ubuntu
+    tag: latest
+    username: *docker_username
+    password: *docker_password
+
+- name: bbr-pcf-pipeline-tasks
+  type: git
+  source:
+    uri: https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks.git
+    branch: main
+    paths: [docker/Dockerfile]
+
+- name: bbr-pcf-pipeline-tasks-final
+  type: registry-image
+  source:
+    tag: final
+    repository: us-west1-docker.pkg.dev/cf-bosh-concourse/bbr-pipeline/bbr-pipeline-tasks
+    username: _json_key
+    password: *gcp_docker_password
+
+- name: oci-build-task-registry-image
+  type: registry-image
+  source:
+    repository: concourse/oci-build-task
+    username: *docker_username
+    password: *docker_password
+
+- name: every-monday
+  type: time
+  icon: timer-outline
+  source:
+    start: 9:00 AM
+    stop: 5:00 PM
+    days: [Monday,Friday]
+    location: Europe/London
 
 jobs:
 - name: system-test-director
@@ -1156,3 +1202,70 @@ jobs:
               popd
             done
           popd
+
+- name: build-bbr-pcf-pipeline-tasks
+  old_name: build-bbr-pcf-pipeline-tasks-rc
+  serial: true
+  plan:
+  - in_parallel:
+    - get: every-monday
+      trigger: true
+    - get: ubuntu-lts
+      params:
+        format: oci
+    - get: bbr-pcf-pipeline-tasks
+      trigger: true
+    - get: oci-build-task-registry-image
+  - task: build-image
+    privileged: true
+    #! It is possible that building an image fails because we hit GH API rate limits.
+    attempts: 3
+    image: oci-build-task-registry-image
+    config:
+      platform: linux
+      run:
+        path: build
+      inputs:
+      - name: bbr-pcf-pipeline-tasks
+      - name: ubuntu-lts
+      outputs:
+      - name: image
+      params:
+        CONTEXT: bbr-pcf-pipeline-tasks/docker
+        IMAGE_ARG_BASE_IMAGE: ubuntu-lts/image.tar
+        UNPACK_ROOTFS: true
+      output_mapping: {image: image-bbr-pcf-pipeline-tasks}
+  - task: test-for-required-binaries
+    image: image
+    config:
+      platform: linux
+      run:
+        path: bash
+        args:
+        - -c
+        - |
+          set -e
+          which om
+          which jq
+          which bosh
+          which ssh
+          which fly
+          which nc
+  - task: write-tag-file
+    image: image
+    config:
+      platform: linux
+      outputs:
+      - name: tag_file
+      run:
+        path: bash
+        args:
+        - -c
+        - |
+          set -e
+          mkdir -p tag_file/
+          echo "final" > tag_file/tag
+  - put: bbr-pcf-pipeline-tasks-final
+    params:
+      image: image/image.tar
+      additional_tags: tag_file/tag
